# -*- coding: utf-8 -*-
"""PPT3 slide content + branding for build_html.py"""
DOC_TITLE = "大模型实践落地"
BRAND_SUB = "实践落地 · 复现"

CONTENT = {
 1: dict(layout="title", section="intro", chip=(None, "CIMICode · 实践分享"),
        data=dict(kicker="大模型实践落地",
                  title="从文字材料到咨询级 PPT 的全流程复现",
                  subtitle="新人照着一步步做，就能用大模型做出一模一样的效果",
                  meta="受众：想用大模型提效的全员　·　讲师：TD Testing",
                  footnote="实战案例：PPT1《入门》+ PPT2《进阶》")),
 2: dict(layout="agenda", section="01", chip=("导览", ""),
        title="直接让大模型做 PPT 会翻车，工程化方法才能稳定出活",
        data=dict(cards=[{"num": "1", "label": "模板化", "desc": "默认卡片堆叠，缺乏咨询级的层级与密度"},
                         {"num": "2", "label": "不可编辑", "desc": "文字烘焙成图片，没法改、没法复用"},
                         {"num": "3", "label": "内容失真", "desc": "AI 编造数据，或把预估当成实测成果"}],
                 roadmap=["证据分析 + 逐页大纲", "8 张样张选风格", "环境核查 + 降级决策",
                          "搭共享视觉模块", "3 页风格验证", "生产 + 渲染 QA + 自检", "方向纠偏"])),
 3: dict(layout="panels", section="03", chip=("认知", "重塑"),
        title="重新认识大模型：它是「能动手的助理」",
        data=dict(grid="repeat(3,1fr)", panels=[
            {"num": "1", "t": "价值在端到端动手", "note": "能读文件、写代码、生成 PPTX、渲染、自检、迭代，把活真正干完"},
            {"num": "2", "t": "环境能力决定路径", "note": "有没有图像生成、有没有渲染器，直接决定能用哪套流程"},
            {"num": "3", "t": "降级不等于失败", "note": "跳过某步没关系，关键是如实告知、留痕、用替代方案保证交付"}],
                 take="把大模型当「能动手的助理」 —— 它的产出是文件、是结果，不只是回答。")),
 4: dict(layout="panels", section="02", chip=("环境", "准备"),
        title="打通渲染链路是第一步 —— 先核查再动手",
        data=dict(grid="repeat(3,1fr)", panels=[
            {"num": "①", "t": "bun + pptxgenjs", "note": "生成 PPTX"},
            {"num": "②", "t": "LibreOffice", "note": "PPTX → PDF"},
            {"num": "③", "t": "PyMuPDF", "note": "PDF → 每页 PNG"}],
                 take="环境核查是「动手前」的动作 —— 链路没打通就开工，必然中途卡死。⚠ LibreOffice 只能导首页 PNG，多页必须走 PDF→PyMuPDF。")),
 5: dict(layout="panels", section="01", chip=("七步", "总览"),
        title="七步工程化流程，让大模型稳定产出可编辑 PPT",
        data=dict(grid="repeat(4,1fr)", panels=[
            {"num": "1", "t": "证据分析", "note": "建证据表、SCR、逐页大纲，第一次确认"},
            {"num": "2", "t": "风格选择", "note": "8 张样张选风格，锁定视觉系统"},
            {"num": "3", "t": "环境核查", "note": "查工具链，缺则如实降级留痕"},
            {"num": "4", "t": "搭模块", "note": "把风格固化成共享视觉模块"},
            {"num": "5", "t": "3 页验证", "note": "先验证视觉执行，再批量生产"},
            {"num": "6", "t": "生产 QA", "note": "PptxGenJS 搭建 + 渲染 + 结构自检"},
            {"num": "7", "t": "方向纠偏", "note": "意图错了果断重写，不修补"}],
                 take="七步是「防翻车」流程 —— 每一步都有确认门或自检，把不确定性逐步消除。")),
 6: dict(layout="panels", section="05", chip=("步骤①", "分析"),
        title="别急着画 —— 先建证据表、写 SCR、定逐页大纲",
        data=dict(grid="1fr 1fr", panels=[
            {"t": "证据表纪律", "items": ["每条事实都标来源", "不用常识补数据", "冲突如实标注", "数字标置信度"]},
            {"t": "第一次确认门（必须一次性）", "items": ["故事线（2-3 条选 1）", "页数 + 逐页论点与结论标题", "每页信息密度与组件清单", "开放数据冲突与 caveat"]}],
                 take="证据表保证内容真实，确认门保证方向对齐 —— 地基稳了，后面的生产才不会塌。⚠ 不能只在「页标题」层面确认，否则后面必返工。")),
 7: dict(layout="panels", section="03", chip=("步骤②", "风格"),
        title="8 张样张直接选，锁定视觉系统再动手",
        data=dict(grid="repeat(4,1fr)", panels=[
            {"num": "1", "t": "经典深红咨询风", "note": ""},
            {"num": "2", "t": "冷灰 + 勃艮第红", "note": ""},
            {"num": "3", "t": "暖象牙 + 暗酒红", "note": ""},
            {"num": "4", "t": "象牙白 + 深蓝 ★", "note": "选定 · 专为科技/AI"},
            {"num": "5", "t": "浅灰白 + 墨绿", "note": ""},
            {"num": "6", "t": "纸张米色 + 铜棕", "note": ""},
            {"num": "7", "t": "浅灰 + 黑金", "note": ""},
            {"num": "8", "t": "冷白灰 + 深紫", "note": ""}],
                 take="一套视觉系统贯穿全系列 —— 锁定色板、15 级 Typography Scale、字体、图表语言，PPT1/2/3 共用风格 4，品牌统一不漂移。")),
 8: dict(layout="compare", section="06", chip=("步骤③", "核查"),
        title="环境缺图像生成？如实降级，留痕继续",
        data=dict(left=dict(tag="🔍 核查发现", h="缺关键能力",
                            items=["无图像生成（ImageGen）能力", "无法生成逐页位图蓝图"]),
                 right=dict(tag="✓ 降级方案", h="跳过蓝图，原生生产 + 渲染 QA",
                            items=["跳过 ImageGen 蓝图（留痕 imagegen_skipped）", "改用 PptxGenJS 原生生产", "LibreOffice 渲染每页 PNG 做 QA", "三原则：如实告知 / 给可选方案 / 留痕继续"]),
                 take="环境限制不是死局 —— 关键是不假装、留痕迹、用替代方案把活交付。")),
 9: dict(layout="config", section="05", chip=("步骤④", "模块"),
        title="把风格固化成模块，多份 PPT 共用一套系统",
        data=dict(why="theme.js —— 改一处，全套跟着变",
                 code=[{"色板": "bg / paper / title / body / accent / warn / pos…"},
                       {"Typography Scale": "15 级（C0 封面 + T1-T14），字号写死"},
                       {"字体": "中文苹方 PingFang SC / 代码 Menlo"},
                       {"元素函数": "addTitle / addFooter / addSoWhat / addKPI / addTable / addPanel"}],
                 path="两份 PPT 共用 theme.js → 统一观感靠函数复用，风格绝不漂移")),
 10: dict(layout="workflow", section="02", chip=("步骤⑤", "验证"),
        title="先做 3 页样张验证，再批量生产",
        data=dict(flow=["做 3 页代表性样张", "渲染每页 PNG", "人审视觉执行", "通过 → 批量生产"],
                 code=["# 3 页样张代表什么", "封面页：C0 大标题 + 字体 + 留白", "内容页：KPI + 卡片 + SO WHAT 密度", "表格页：表头 + 代码块样式"],
                 take="3 页验证是「风险闸门」 —— 用最小成本确认视觉执行，再放心量产，避免 35 页返工。")),
 11: dict(layout="panels", section="04", chip=("步骤⑥", "生产"),
        title="PptxGenJS 原生搭建 + 渲染 QA + 结构自检",
        data=dict(grid="1fr 1fr", panels=[
            {"t": "生产循环（每份 PPT 走一遍）", "items": ["bun run build-x.js → 生成 PPTX", "bash render.sh → 每页 PNG", "python 结构自检 → 零尺寸 / 越界", "渲染图发人审 → 有问题就修"]},
            {"t": "结构自检（复现必备）", "items": ["遍历 shapes 量 left/top/width/height", "w≤0 或 h≤0 → 报「零尺寸」", "l+w>W → 报「右越界」", "用脚本查，不靠肉眼 —— 又快又准"]}],
                 take="生产不是「生成完就交」 —— 100% 原生对象、0 图片、完全可编辑；渲染 + 自检 + 人审三道关，才保证每页都合格。")),
 12: dict(layout="panels", section="07", chip=("步骤⑦", "纠偏"),
        title="发现意图理解错，果断重写",
        data=dict(grid="repeat(3,1fr)", panels=[
            {"num": "1", "t": "源材料标题 ≠ 真实意图", "note": "材料叫「成本优化」，但用户要「用好」 —— 要挖到真实目的"},
            {"num": "2", "t": "重写前先确认新结构", "note": "已经错过一次，新方向必须再确认，避免二次跑偏"},
            {"num": "3", "t": "不在错误方向上修补", "note": "方向错就推翻重来，别在小修小补上浪费时间"}],
                 take="方向纠偏不是失败，而是流程的一部分 —— 早发现、早重写，比硬撑到底省得多。（本会话 PPT2 从「成本」重写为「用好」）")),
 13: dict(layout="grid6", section="03", chip=("方法", "论"),
        title="六条核心实践，让大模型协作又稳又快",
        data=dict(grid=[{"n": "1", "t": "证据表先行", "d": "每个事实标来源，不臆造、不用常识补"},
                        {"n": "2", "t": "确认门要重", "d": "故事线 / 页数 / 论点 / 密度一次确认"},
                        {"n": "3", "t": "先验证再量产", "d": "3 页样张确认视觉，再批量生产"},
                        {"n": "4", "t": "结构自检", "d": "脚本查零尺寸 / 越界，不靠肉眼"},
                        {"n": "5", "t": "局限要诚实", "d": "AI 无法读图交人审；缺能力就降级留痕"},
                        {"n": "6", "t": "错了果断重写", "d": "意图错就推翻重来，不修补"}],
                 take="六条方法论是「防翻车护栏」 —— 每一条都来自本会话的真实教训。")),
 14: dict(layout="panels", section="07", chip=("避坑", "指南"),
        title="七个坑及解法 —— 别再踩一次",
        data=dict(grid="repeat(4,1fr)", panels=[
            {"num": "1", "t": "直接让做 PPT → 模板化", "note": "解：先证据分析 + 逐页大纲"},
            {"num": "2", "t": "LibreOffice 只导首页 PNG", "note": "解：改走 PDF → PyMuPDF 切页"},
            {"num": "3", "t": "缺图像生成硬撑", "note": "解：如实降级、留痕、换方案"},
            {"num": "4", "t": "不验证就量产", "note": "解：先做 3 页样张"},
            {"num": "5", "t": "生成完就交", "note": "解：渲染 + 结构自检 + 人审"},
            {"num": "6", "t": "确认门只在页标题层", "note": "解：故事线 / 页数 / 密度一次确认"},
            {"num": "7", "t": "方向错了还修补", "note": "解：果断重写，删旧版"}],
                 take="踩坑不可怕 —— 记下来、有解法，新人就能直接绕过。")),
 15: dict(layout="checklist", section="06", chip=("复现", "指南"),
        title="照这 6 阶段做，新手也能复现",
        data=dict(items=["A 准备：装 bun/pptxgenjs/LibreOffice + python-pptx/PyMuPDF，跑环境核查",
                         "B 分析：建证据表 + 脑暴故事线选 1 + 写 SCR 与逐页大纲 + 确认门拍板",
                         "C 定风格：展示 8 张样张 + 选定风格 + 锁色板/字体/图标",
                         "D 模块 + 验证：写共享视觉模块 + 做 3 页样张 + 渲染确认",
                         "E 生产：逐页 PptxGenJS 搭建 + 渲染 + 结构自检 + 人审定稿",
                         "F 校准：方向不对→确认新结构 + 果断重写 + 删旧版",
                         "把 theme.js 存成团队资产",
                         "沉淀你自己的踩坑清单"],
                 next="Checklist 把「经验」变成「步骤」 —— 新人照着勾，就能走完全程。")),
 16: dict(layout="demo2", section="04", chip=("成果", "交付"),
        title="实战成果：两份可编辑咨询级 PPT",
        data=dict(demos=[{"t": "PPT1《公司大模型工具使用入门》", "prompt": "17 页 · 面向新人 · 手把手教学：模型一览 / 权限安装 / 核心概念 / Plan-Build / 六大场景 / 6 个 Demo / AGENTS.md / Skill / 安全 / FAQ / Checklist", "out": "新人当天独立完成首个任务"},
                         {"t": "PPT2《用好大模型：进阶与团队落地》", "prompt": "18 页 · 面向 TL/资深 · 团队赋能：五板斧 / 4 高价值场景（DOE / 调研 / 项目 / 沉淀）/ 提效配置 / 团队规范 / 落地路线图 / 效果信号", "out": "团队从「会聊」到「用好」"}],
                 take="同一套流程、同一套风格，产出系列化交付物 —— 改文案 / 换主题 / 加页数都能复用 theme.js + render.sh + build 模板。")),
 17: dict(layout="checklist", section="end", chip=(None, "收束 · 行动"),
        title="把「个人会用」变成「团队会做」",
        data=dict(items=["装好环境，打通渲染链路", "用一份小材料跑通七步流程", "把 theme.js 存成团队资产", "沉淀你自己的踩坑清单"],
                 next="一句话：大模型不是聊天机器人，而是「能动手的助理」 —— 用工程化方法把它变成可复现的生产力。　|　三份配套：PPT1 入门 · PPT2 进阶 · PPT3 实践落地")),
}
