# -*- coding: utf-8 -*-
"""PPT2 slide content + branding for build_html.py"""
DOC_TITLE = "进阶应用与团队落地"
BRAND_SUB = "用好大模型 · 进阶"

CONTENT = {
 1: dict(layout="title", section="intro", chip=(None, "CIMICode · 进阶培训"),
        data=dict(kicker="CIMICode 进阶应用与团队落地",
                  title="用好大模型",
                  subtitle="从「会聊」到「用好」，让团队真正发挥大模型价值",
                  meta="受众：TL、组内资深工程师　·　讲师：TD Testing",
                  footnote="配套：《公司大模型工具使用入门》(PPT1)")),
 2: dict(layout="agenda", section="01", chip=("导览", ""),
        title="三大进阶痛点，五板斧破局",
        data=dict(cards=[{"num": "1", "label": "输出不稳", "desc": "没配背景 / 术语，大模型望文生义，反复返工"},
                         {"num": "2", "label": "重复造轮子", "desc": "每个人各写各的 Prompt，经验无法沉淀复用"},
                         {"num": "3", "label": "水平参差", "desc": "新人不会问、老人不会教，团队能力断层"}],
                 roadmap=["选对模型（按任务选型）", "配好 AGENTS.md（人设与术语）", "写好 Prompt（具体 + 结构化）",
                          "用对工作流与工具（Plan-Build + Skill）", "团队规范落地（统一配置 + 复用）"])),
 3: dict(layout="panels", section="01", chip=("板斧①", "选对模型"),
        title="按任务选模型：简单归 Flash、复杂归高阶",
        data=dict(grid="2fr 3fr", panels=[
            {"t": "默认：DeepSeek Flash", "note": "成本极低、响应快，覆盖绝大多数日常任务"},
            {"t": "何时升高阶？", "items": ["多次改代码仍未解决", "逻辑推理陷入死循环", "长文档 / 海量对比任务"]}],
                 take="选型不是越强越好 —— 把深度推理能力留给真正复杂的任务，日常交给 Flash 快速完成。")),
 4: dict(layout="config", section="05", chip=("板斧②", "配好 AGENTS.md"),
        title="AGENTS.md 让大模型秒懂半导体专业语义",
        data=dict(why="消歧义 + 完整四段模板，从第一次响应就理解术语",
                 code=[{"# Role & Background": "半导体先进封装 TD Testing 高级测试工程师（测试 Flow / 自动化 / 数据分析）"},
                       {"# Terminology & Context": "Pre-DC / CPK / Yield / DOE / SECS-GEM / Prober 等术语"},
                       {"# Coding & Response Style": "优先 Python + pandas，异常处理健壮，结果导向"},
                       {"# Safety & Constraints": "产线操作先确认安全步骤，改动前先备份"}],
                 path="路径：~/.cimi/cimicode/AGENTS.md　·　一次配置，永久生效")),
 5: dict(layout="panels", section="05", chip=("板斧②", "双层配置"),
        title="全局 + 项目级双层配置，兼顾通用与专用",
        data=dict(grid="1fr 1fr", panels=[
            {"t": "全局配置", "note": "~/.cimi/cimicode/AGENTS.md　·　对所有项目生效",
             "items": ["角色背景与术语（打底）", "通用编码与回复风格", "团队统一的红线约束"]},
            {"t": "项目级配置", "note": "<项目目录>/AGENTS.md　·　仅对该项目生效（同名覆盖全局）",
             "items": ["项目信息：机型 / 测试项", "数据目录结构：logs / data / scripts", "特殊要求：UTF-8、UTC+8"]}],
                 take="全局打底 + 项目叠加 —— 通用规范一次写好，项目细节随用随加，团队不再各写各的。")),
 6: dict(layout="compare", section="03", chip=("板斧③", "写好 Prompt"),
        title="信息越具体，输出越准确",
        data=dict(left=dict(tag="✗ 模糊", h="帮我排查这个测试机报错。",
                            items=["不知道机台型号", "不知道 Log 位置", "不知道测试项与现象", "→ 输出通用步骤，不具针对性"]),
                 right=dict(tag="✓ 具体", h="Accretech 探针台 Pre-DC 报 ERR-2041 Contact Resistance Exceeded。",
                            code=["Wafer 第3次Pass，Pin: Row A-F Col 1-12",
                                  "Log: ./logs/prober_20260726.txt",
                                  "请分析 ERR-2041 前后 Pin 坐标，",
                                  "识别高阻 Die，生成 Python 散点图。"]),
                 take="机台、错误码、坐标范围、Log 路径都给全 —— 才能从「通用答案」升级到「可直接用的方案」。")),
 7: dict(layout="panels", section="03", chip=("板斧③", "结构化提问"),
        title="用「背景 / 目标 / 约束 / 输入 / 输出」五段式提问",
        data=dict(grid="3fr 2fr", panels=[
            {"t": "五段式模板", "items": ["【背景】项目 / 场景 / 技术栈 / 已有条件", "【目标】期望功能与输出格式",
                                       "【约束】性能 / 兼容性 / 安全限制", "【输入】数据 / 代码 / 配置位置", "【输出】文件格式 / 保存位置 / 是否测试"]},
            {"t": "3 个优化技巧", "items": ["提供示例：给一行期望格式", "分步骤指令：读→筛选→统计→导出", "明确输出格式：语言 / 库 / 文件名"]}],
                 take="五段式是可复用的提问框架 —— 团队统一用它，输出质量与一致性都能稳定提升。")),
 8: dict(layout="workflow", section="02", chip=("板斧④", "工作流"),
        title="Plan 5 步规划审核，Build 自动落地执行",
        data=dict(flow=["理解需求", "拆解任务", "设计架构", "评估风险", "生成 TODO.md"],
                 code=["# 测试数据自动化分析平台", "架构: pandas + SQLAlchemy / matplotlib / HTML+PDF",
                       "Phase1 基础框架 · Phase2 可视化 · Phase3 报告", "风险: 数据格式不一致→清洗层；大数据量→分块",
                       "→ 工程师审核 Plan：通过进 Build；有问题回 Plan"],
                 take="Plan 让「做不做、怎么做」先想清楚 —— 减少返工，复杂项目稳步推进，团队协作更高效。")),
 9: dict(layout="skills2", section="02", chip=("板斧④", "Skill 工具"),
        title="Grill-Me 厘清需求，Web Search 补时效",
        data=dict(skills=[{"t": "Grill-Me　需求澄清", "d": "用 5 类反问厘清需求：Log 格式、关键字段、输出格式、是否统计、是否可视化，帮你把问题问全。", "cmd": "$ /install-skill grill-me"},
                          {"t": "Web Search　联网搜索", "d": "查最新 API 文档与库版本、行业最佳实践、类似报错方案、JEDEC 等标准更新 —— 让知识不过期。", "cmd": "$ /install-skill web-search"}],
                 take="Grill-Me 把模糊需求变完整需求，Web Search 把过时知识变最新信息 —— 双 Skill 让团队用好工具。")),
 10: dict(layout="concepts", section="04", chip=("场景", "实战"),
        title="喂对数据，让大模型设计可执行 DOE 实验",
        data=dict(center="已有数据 → 数据分析 → 识别问题 → 设计 DOE",
                 concepts=[{"n": "①", "t": "读项目文件", "d": "指定 ./data/rc_data.csv 路径"},
                           {"n": "②", "t": "粘贴关键数据", "d": "批次统计表（样本 / 均值 / CPK）"},
                           {"n": "③", "t": "提供文件路径", "d": "原始 + 处理后 + 配置文件"}]),
        take="把测试数据 + 失效机制喂给大模型 —— 直接产出可执行的实验矩阵，DOE 周期显著缩短。"),
 11: dict(layout="panels", section="04", chip=("场景", "实战"),
        title="技术难题没思路？让大模型做调研与头脑风暴",
        data=dict(grid="3fr 2fr", panels=[
            {"t": "场景：探针针尖磨损致虚焊", "note": "明确失效机制 + 要求多方案对比 + 要求决策维度",
             "items": ["检索工业界解决 Micro-bump 探针损伤的主流方案", "列 5 个头脑风暴方向", "对比利弊与引入成本，给推荐路径（可用 web-search）"]},
            {"t": "预期产出", "items": ["技术方案对比表（5 方向）", "各方案利弊分析", "引入成本评估", "推荐实施路径"]}],
                 take="从「没思路」到「5 方向对比 + 推荐路径」 —— 把经验型难题快速拆成可决策的清单。")),
 12: dict(layout="workflow", section="04", chip=("场景", "实战"),
        title="复杂系统一句话起步：Plan-Build 全流程示范",
        data=dict(flow=["一句话讲清 5 项需求", "Plan 自动拆解架构", "Build 自动建目录写代码"],
                 code=["# 测试数据自动化分析平台", "支持 CSV/Excel/SQLite · CPK 趋势 / Yield 分布",
                       "历史对比 · 异常报警 · HTML + PDF 报告", "Build：自动建目录、写代码、跑测试、出报告"],
                 take="复杂系统不必从零手敲 —— Plan 拆解 + Build 自动落地，把「周级」开发压缩到「天级」。")),
 13: dict(layout="panels", section="04", chip=("场景", "实战"),
        title="把经验沉淀成手册：排查手册 / SOP / 培训材料",
        data=dict(grid="repeat(4,1fr)", panels=[
            {"num": "①", "t": "排查手册", "note": "常见报错的原因 / 步骤 / 解决 / 预防"},
            {"num": "②", "t": "测试 SOP", "note": "机台操作与测试 Flow 标准化"},
            {"num": "③", "t": "培训材料", "note": "新人上手 PPT / 文档"},
            {"num": "④", "t": "脚本库", "note": "可复用的自动化脚本集合"}],
                 take="把「个人经验」沉淀为「团队资产」 —— 手册、SOP、脚本库让新人快速接班，不再依赖单点。")),
 14: dict(layout="panels", section="06", chip=("提效", "与规范"),
        title="Auto-Approve + 会话复用，把重复操作清零",
        data=dict(grid="1fr 1fr", panels=[
            {"t": "Auto-Approve · 自动执行", "items": ["个人开发环境 / 独立分支可放开", "⚠ 产线数据库删除、线上配置严禁全局免确认", "完成任务后及时关闭"]},
            {"t": "会话复用三招", "items": ["保存常用对话模板，下次直接复用", "利用会话历史延续讨论，不重复输入上下文", "方向错误果断重启，避免越聊越偏"]}],
                 take="个人环境放开提效、产线严守确认；会话模板化让团队的重复输入清零，专注判断与决策。")),
 15: dict(layout="panels", section="06", chip=("团队", "规范"),
        title="统一配置 + 模板库 + 审查，拉齐团队水平",
        data=dict(grid="repeat(4,1fr)", panels=[
            {"num": "1", "t": "统一部门级 AGENTS.md", "note": "全员共用术语与角色背景，输出一致"},
            {"num": "2", "t": "共享 Prompt 模板库", "note": "高频任务的五段式模板沉淀进知识库"},
            {"num": "3", "t": "定期经验分享会", "note": "复盘好用案例与踩坑，扩散给全团队"},
            {"num": "4", "t": "代码审查机制", "note": "AI 生成代码也走 review，守住质量"}],
                 take="规范不是限制，而是放大器 —— 一套统一配置 + 模板库，让新人的起点就是团队的最高水平。")),
 16: dict(layout="phases", section="06", chip=("团队", "落地"),
        title="4 阶段推进，从基础建设到持续优化",
        data=dict(phases=[
            {"tag": "Phase 1", "t": "基础建设", "dur": "第 1-2 周", "items": ["全员申请权限", "安装桌面版 + 终端版", "统一配置 AGENTS.md", "安装基础 Skill"]},
            {"tag": "Phase 2", "t": "技能培训", "dur": "第 3-4 周", "items": ["组织使用培训", "分享最佳实践", "建立反馈机制", "制定使用规范"]},
            {"tag": "Phase 3", "t": "深度应用", "dur": "第 5-8 周", "items": ["推广 Plan-Build", "建立脚本库", "沉淀 SOP 文档", "推广高价值场景"]},
            {"tag": "Phase 4", "t": "持续优化", "dur": "长期", "items": ["定期复盘效果", "优化配置", "扩展 Skill 场景", "分享最佳实践"]}],
                 take="4 阶段渐进 —— 先把基建和规范立起来，再推深度场景，避免一哄而上导致水平参差。")),
 17: dict(layout="grid6", section="06", chip=("团队", "落地"),
        title="怎么看团队真的「用好」了？",
        data=dict(grid=[{"n": "①", "t": "Plan-Build 采用率", "d": "复杂任务是否普遍先 Plan 再 Build"},
                        {"n": "②", "t": "脚本 / 模板复用数", "d": "共享库里沉淀了多少可复用资产"},
                        {"n": "③", "t": "AGENTS.md 配置完整度", "d": "部门级 + 项目级是否到位"},
                        {"n": "④", "t": "新人独立上手速度", "d": "从入职到完成首个任务的时间"},
                        {"n": "⑤", "t": "知识沉淀量", "d": "SOP / 手册 / 培训材料的产出"},
                        {"n": "⑥", "t": "问题复现率下降", "d": "同类报错是否靠手册自助解决"}],
                 take="不追求好看的数字，而看真实的采用与沉淀 —— 信号持续向好，就是团队「用好」的证据。")),
 18: dict(layout="checklist", section="end", chip=(None, "收束 · 立即行动"),
        title="五板斧 + 4 阶段，让全团队用好大模型",
        data=dict(items=["统一部门级 AGENTS.md（本周）", "完成全员 Skill 安装（下周）", "组织 CIMICode 使用培训",
                         "推广 Plan-Build 工作流", "沉淀首批 Prompt 模板与脚本库", "分享首批最佳实践（第 4 周）",
                         "启动 Phase 1 基础建设", "建立效果信号看板"],
                 next="入门教「开通上手」→ PPT1　|　进阶教「用好赋能」→ 本课 PPT2　|　实践落地 → PPT3")),
}
